-- MySQL Script generated by MySQL Workbench
-- Wed Jul 27 19:42:47 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(60) NOT NULL,
  `telefono` VARCHAR(20) NOT NULL,
  `correo` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `planes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `planes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(70) NOT NULL,
  `fechainicio` DATE NOT NULL,
  `fechafinal` DATE NOT NULL,
  `precio` DOUBLE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ciudad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciudad` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `servicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `servicios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(50) NOT NULL,
  `valor` DOUBLE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asesor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(60) NOT NULL,
  `telefono` VARCHAR(20) NOT NULL,
  `correo` VARCHAR(60) NOT NULL,
  `salario` DOUBLE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `factura` (
  `id` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `valor` DOUBLE NOT NULL,
  `planes_id` INT NOT NULL,
  `cliente_id` INT NOT NULL,
  `asesor_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_viajes_planes1_idx` (`planes_id` ASC),
  INDEX `fk_viajes_cliente1_idx` (`cliente_id` ASC),
  INDEX `fk_viajes_asesor1_idx` (`asesor_id` ASC),
  CONSTRAINT `fk_viajes_planes1`
    FOREIGN KEY (`planes_id`)
    REFERENCES `planes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_viajes_cliente1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_viajes_asesor1`
    FOREIGN KEY (`asesor_id`)
    REFERENCES `asesor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `detalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `detalle` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `valor` DOUBLE NOT NULL,
  `cantidad` TINYINT NOT NULL,
  `servicios_id` INT NOT NULL,
  `ciudad_id` INT NOT NULL,
  `factura_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_paquete_servicios1_idx` (`servicios_id` ASC),
  INDEX `fk_paquete_ciudad1_idx` (`ciudad_id` ASC),
  INDEX `fk_paquete_viajes1_idx` (`factura_id` ASC),
  CONSTRAINT `fk_paquete_servicios1`
    FOREIGN KEY (`servicios_id`)
    REFERENCES `servicios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_paquete_ciudad1`
    FOREIGN KEY (`ciudad_id`)
    REFERENCES `ciudad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_paquete_viajes1`
    FOREIGN KEY (`factura_id`)
    REFERENCES `factura` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pagos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pagos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `valor` DOUBLE NOT NULL,
  `tipo` VARCHAR(20) NOT NULL,
  `observacion` VARCHAR(50) NULL,
  `factura_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pagos_factura1_idx` (`factura_id` ASC),
  CONSTRAINT `fk_pagos_factura1`
    FOREIGN KEY (`factura_id`)
    REFERENCES `factura` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `ciudad`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `ciudad` (`id`, `nombre`) VALUES (1, 'BARRANQUILLA');
INSERT INTO `ciudad` (`id`, `nombre`) VALUES (2, 'BOGOTA');
INSERT INTO `ciudad` (`id`, `nombre`) VALUES (3, 'CARTAGENA');
INSERT INTO `ciudad` (`id`, `nombre`) VALUES (4, 'SANTA MARTA');
INSERT INTO `ciudad` (`id`, `nombre`) VALUES (5, 'MANIZALES');

COMMIT;


-- -----------------------------------------------------
-- Data for table `servicios`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `servicios` (`id`, `descripcion`, `valor`) VALUES (1, 'Alojamiento en Hotel Todo inluido', 250000);
INSERT INTO `servicios` (`id`, `descripcion`, `valor`) VALUES (2, 'Tiquetes Aereo Clase Económica', 800000);
INSERT INTO `servicios` (`id`, `descripcion`, `valor`) VALUES (3, 'Entrada Castillo San felipe Cartagena', 10000);

COMMIT;

